### PR TITLE
Add a segment about IRB.

### PR DESCRIPTION
**Pull request by arokem**
NOTE: This is only important for *research*, not for evaluation. Does this
come across clearly?

### CODE REVIEW

**Comment by dhuppenkothen** [comment]
Comes clearly through enough for me. There may be a point to be made that I think IRBs are specifically American? I'm sure universities in other countries might have similar institutions, but I don't know what the rules would be or what they'd be called.

**Comment by arokem** [comment]
I've seen them called "Human Subject Committees" and "Helsinki committees"  (because of this: https://en.wikipedia.org/wiki/Declaration_of_Helsinki). But the general principle is international. Should I add anything?

**Comment by dhuppenkothen** [comment]
maybe just something like "or equivalent bodies at non-US institutions"?

**Review by dhuppenkothen — APPROVED** [review]
LGTM

**Comment by arokem** [comment]
Addresses #41

**Pull request merged**
