### PR TITLE
Rephrased the what section and moved some stuff there from intro

### PR DESCRIPTION
**Pull request by dhuppenkothen**
I sat down for an hour today and tried to synthesize everything we've been talking about with respect to summer schools versus hackathons and hack weeks and made a nice big table with all the similarities/differences. 

Then I sat down and tried to write it all out. Comments welcome ("scrap and go back to previous version" is a totally valid one :)).

### CODE REVIEW

**Comment by arokem** [comment]
I think this is really great, and sharpens the distinction while doing exactly what the reviewer wanted (pointing out strengths and weaknesses of each). 

I wonder whether some of it could be merged into the "design" section (or vice versa). I am thinking particularly about the paragraph that starts with "There is, however, a major risk in the lack of focus: by wanting...". I think that some of these ideas are repeated in the design section. Maybe just a short pointer here, and a more extended discussion in the design section (or vice versa)?

**Comment by dhuppenkothen** [comment]
@arokem I am conflicted about this. I agree that some of this may fit thematically better in the design section, but I'm worried that it'll have less of a logical flow in terms of the comparison then. I could be convinced either way, I think. :)

**Comment by arokem** [comment]
I agree that it flows well as is. Maybe reduce repetition in the design section?

**Comment by dhuppenkothen** [comment]
I moved around bits from the design section, but I actually think stating twice that hack weeks require careful facilitation is not a bad thing. :)

**Pull request merged**
