### PR TITLE
Compare to summer schools

### PR DESCRIPTION
**Pull request by arokem**
Making the comparison to summer schools more nuanced. Will continue to work on this in other parts of the manuscript.

### CODE REVIEW

**Comment by arokem** [comment]
OK - I think that I am done here.

**Comment by dhuppenkothen** [comment]
Do we have the figure in eps format? I don't remember whether this was one of the journals that required figures in eps, but I've run into this issue before ...

**Comment by arokem** [comment]
I don't have the figure in eps. I created it with google drive's drawing software, which doesn't have an eps export option. Any ideas how to convert png => eps?

**Comment by dhuppenkothen** [comment]
Ok, I looked it up: "Resolution of at least 300 dpi for all figures is required. EPS, high-resolution PDF, and PowerPoint are preferred formats for figures that will be used in the main text"

from [the submission guidelines](http://www.pnas.org/page/authors/submission)

**Comment by dhuppenkothen** [comment]
I am going to merge this.

**Comment by karthik** [comment]
> Any ideas how to convert png => eps?

I can help with this if its still an issue.

**Comment by dhuppenkothen** [comment]
should be fixed, but thanks :)

**Pull request merged**
