### PR TITLE
Additional stats + tweaks

### PR DESCRIPTION
**Pull request by dhuppenkothen**
Turns out nobody can agree on how to do statistics on surveys, so I picked something that seemed vaguely sensible and ran with it.

There's a new table (because reporting these results in line turned out to be unreadable), and I added some figures to the supplementary materials, and I rewrote a bunch of text in the results section.

Still working on rewordings and stuff, so it's not quite ready to merge.

### CODE REVIEW

**Comment by dhuppenkothen** [comment]
Added some more tweaks to language and responses to the reviewer's comments. I think this is ready for review.

**Comment by arokem** [comment]
This is a lot of numbers for what is basically a bunch of null results. Maybe we can replace the table with a sentence stating that we found no statistically significant correlations? Is there any statistics we could do on the scores themselves? For example for the null hypothesis that the scores are uniformly distributed?

**Comment by dhuppenkothen** [comment]
Added the PDF version of Figure 1, and reordered the participant selection section. @arokem @aaarendt could you have a look before I merge whether it flows more logically, as we discussed earlier?

There's a reference I need to chase up, other than that I think this is about ready for merging. :)

**Comment by dhuppenkothen** [comment]
I'm going to merge this so we can edit off master. :)

**Pull request merged**
